language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
before_script:
  - composer self-update
  - composer update --no-interaction
script:
  - vendor/bin/phing
